// Retake the deck screenshots that changed after the UI fixes (Arabic, 1280x800 @2x).
import { chromium } from "playwright";
const EXE = `${process.env.HOME}/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing`;
const OUT = "../docs/screenshots";
const b = await chromium.launch({ executablePath: EXE });
const p = await (await b.newContext({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 2, locale: "ar" })).newPage();
const sleep = (ms) => p.waitForTimeout(ms);
await p.goto("https://shahada.theislam.chat/ar?demo=shahada", { waitUntil: "load", timeout: 90000 });
await p.getByText("ما فهمناه منك").first().waitFor({ timeout: 90000 });
await p.getByRole("button", { name: "متابعة" }).first().click();
await p.getByRole("button", { name: "أكمل المنهج" }).first().waitFor({ timeout: 90000 });
await p.getByRole("button", { name: "أكمل المنهج" }).first().click();
await p.getByText("ماذا تحب أن تتعلم أولاً").first().waitFor({ timeout: 60000 });
await p.getByRole("button", { name: "الوضوء" }).first().click();
await sleep(4000);
await p.getByRole("button", { name: "الدرس التالي" }).last().click();
await p.getByText("الخطوات بلفظ الكتاب").first().waitFor({ timeout: 60000 });
await p.getByText("الخطوات بلفظ الكتاب").first().scrollIntoViewIfNeeded();
await p.evaluate(() => window.scrollBy(0, -120));
await sleep(1200);
await p.screenshot({ path: `${OUT}/03-wudu-steps-exercises.png` });
const ask = async (q) => { const c = p.locator("textarea, input[type=text]").last(); await c.click(); await c.fill(q); await p.keyboard.press("Enter"); };
await ask("ما نواقض الوضوء؟");
await p.getByText(/هذا من درس/).last().waitFor({ timeout: 90000 });
await p.getByText(/هذا من درس/).last().scrollIntoViewIfNeeded();
await p.evaluate(() => window.scrollBy(0, 200));
await sleep(1000);
await p.screenshot({ path: `${OUT}/04-answer-with-sources.png` });
await ask("ما أنصبة البنات في الميراث؟");
await p.getByText(/لم أجد جواب/).last().waitFor({ timeout: 90000 });
await p.getByText(/لم أجد جواب/).last().scrollIntoViewIfNeeded();
await sleep(1000);
await p.screenshot({ path: `${OUT}/05-not-in-book.png` });
await b.close();
console.log("shots ok");
