// Desktop (Arabic): Al-Fatiha path (listen & repeat), a personal question handed to a mentor ([VIDEO] demo case),
// the mentor platform answering it (recorded separately), the reply in the learning space, then the emergency banner.
import { session, BASE } from "./lib.mjs";
const L = await session("learner");
const { page, mark, sleep, smooth } = L;
const ask = async (q) => { const box = page.getByPlaceholder(/اكتب سؤالك/).first(); await box.click(); await box.pressSequentially(q, { delay: 45 }); await sleep(300); await page.keyboard.press("Enter"); };
await page.goto(`${BASE}/ar?demo=shahada`, { waitUntil: "load", timeout: 90000 });
await page.getByRole("button", { name: /ابدأ رحلتك/ }).first().click({ timeout: 60000 });
await sleep(2000);
await page.getByRole("button", { name: "متابعة" }).first().click(); await sleep(1500);
await page.getByRole("button", { name: /^الفاتحة/ }).last().click();
await page.getByText("الدرس باختصار").first().waitFor({ timeout: 60000 }); await sleep(1500);
await page.getByRole("button", { name: /أتممت الدرس، التالي/ }).first().click();
await sleep(6000);
mark("fatiha");
console.log("FATIHA BTNS", (await page.$$eval("main button, [role=dialog] button", (e) => e.filter(x=>x.offsetParent).map((x) => (x.getAttribute("aria-label")||x.innerText||"").trim().replace(/\s+/g," ").slice(0,40)))).join(" | "));
const lr = page.getByText(/استمع وردّد|استمع ورد|ردّد/).first();
await lr.scrollIntoViewIfNeeded().catch((e) => console.log("lr", e.message));
await sleep(600);
mark("listen");
await page.getByRole("button", { name: /استمع|تشغيل|شغّل/ }).first().click().catch((e) => console.log("play", e.message));
await sleep(5000);
mark("personal");
await ask("زوجتي ما زالت على دينها، هل زواجنا صحيح الآن؟");
await page.getByText(/تخص حالتك|مرشد/).last().waitFor({ timeout: 90000 }).catch(() => {});
await sleep(9000);
mark("referral");
await sleep(2500);
await page.getByRole("button", { name: "تحدث إلى إنسان" }).last().click();
await sleep(1500);
await page.getByRole("button", { name: /مرشد أخ/ }).first().click(); await sleep(800);
const ta = page.locator("[role=dialog] textarea, .modal textarea").last();
await page.getByLabel(/سؤالك أو رسالتك/).first().fill("[VIDEO] مشهد تجريبي للفيلم: زوجتي ما زالت على دينها، هل زواجنا صحيح الآن؟").catch(async (e) => { console.log("msg", e.message); });
await sleep(800);
await page.getByLabel(/أوافق على إرسال/).first().check({ force: true }).catch((e) => console.log("consent", e.message));
await sleep(800);
mark("handoff_send");
await page.getByRole("button", { name: "أرسل إلى مرشد" }).first().click().catch((e) => console.log("send", e.message));
await sleep(3500);
mark("handoff_sent");
await page.getByRole("button", { name: "إغلاق" }).last().click().catch(() => {});
await sleep(1000);

// Mentor platform (its own recording)
const M = await session("mentor");
const mp = M.page;
await mp.goto(`${BASE}/mentor`, { waitUntil: "load", timeout: 90000 });
await M.sleep(1500);
M.mark("login");
const email = mp.locator("input[type=email], input[name*=mail i], input[autocomplete=username]").first();
await email.click(); await email.pressSequentially("supervisor@demo.theislam.chat", { delay: 25 });
await mp.locator("input[type=password]").first().fill(process.env.MENTOR_PASSWORD);
await M.sleep(500);
await mp.getByRole("button", { name: "دخول" }).first().click();
await M.sleep(5000);
M.mark("inbox");
console.log("MENTOR INBOX", (await mp.evaluate(() => document.body.innerText)).slice(0, 2500));
await M.sleep(3000);
await mp.getByText(/\[VIDEO\]/).first().click().catch((e) => console.log("case", e.message));
await M.sleep(4000);
M.mark("case");
console.log("MENTOR CASE", (await mp.evaluate(() => document.body.innerText)).slice(0, 2500));
const rbox = mp.locator("textarea").last();
await rbox.click().catch(() => {});
await rbox.pressSequentially("وعليكم السلام أخي الكريم، أنا هنا لأساعدك. هذه مسألة تحتاج تفصيلاً، فأخبرني متى يناسبك أن نتحدث.", { delay: 20 }).catch((e) => console.log("reply", e.message));
await M.sleep(800);
M.mark("reply_send");
await mp.getByRole("button", { name: /أرسل|إرسال/ }).last().click().catch((e) => console.log("rsend", e.message));
await M.sleep(4000);
M.mark("reply_sent");
await M.done();

await page.getByText(/أنا هنا لأساعدك/).last().waitFor({ timeout: 60000 }).catch((e) => console.log("noreply", e.message));
await page.getByText(/أنا هنا لأساعدك/).last().scrollIntoViewIfNeeded().catch(() => {});
await sleep(500);
mark("reply_arrived");
await sleep(4000);
mark("crisis");
await ask("أريد أن أنتحر");
await sleep(12000);
mark("crisis_banner");
await sleep(4000);
await L.done();
