// Mentor platform on a LOCAL run of the service (http://localhost:8799, synthetic demo cases, demo password from config defaults).
import { session } from "./lib.mjs";
const BASE = process.env.MBASE ?? "http://localhost:8799";
const { page, mark, sleep, smooth, done } = await session("mentor");
await page.goto(`${BASE}/mentor`, { waitUntil: "load", timeout: 60000 });
await sleep(1000);
const email = page.locator("input[type=email], input[name*=mail i], input[autocomplete=username]").first();
await email.click(); await email.pressSequentially("supervisor@demo.theislam.chat", { delay: 20 });
await page.locator("input[type=password]").first().fill(process.env.LOCAL_MENTOR_PASSWORD ?? "mentor-demo");
await page.getByRole("button", { name: "دخول" }).first().click();
await sleep(4000);
mark("inbox");
console.log("INBOX", (await page.evaluate(() => document.body.innerText)).slice(0, 1800));
await sleep(4000);
const row = page.getByText(/أنا معك، وسلامتك/).first();
await row.click().catch((e) => console.log("row", e.message));
await sleep(3500);
mark("case");
console.log("CASE", (await page.evaluate(() => document.body.innerText)).slice(0, 1800));
await sleep(2500);
const rbox = page.locator("textarea").last();
await rbox.scrollIntoViewIfNeeded().catch(() => {});
await rbox.click().catch(() => {});
mark("reply");
await rbox.pressSequentially("أنا معك، وسلامتك أهم شيء الآن. هل أنت في مكان آمن؟", { delay: 30 }).catch((e) => console.log("type", e.message));
await sleep(800);
await page.getByRole("button", { name: /^أرسل|إرسال/ }).last().click().catch((e) => console.log("send", e.message));
await sleep(3500);
mark("sent");
await done();
