// Desktop (English) learning space: same actions as rec_ls.mjs on /en. Writes raw/ls_en.webm + raw/ls_en.json (same mark names).
import { session, BASE } from "./lib.mjs";
const { page, mark, sleep, smooth, done } = await session("ls_en", { locale: "en" });
const ask = async (q) => {
  const box = page.getByPlaceholder(/question|ask/i).first();
  await box.click().catch(async (e) => { console.log("askbox", e.message); });
  await box.pressSequentially(q, { delay: 45 }).catch((e) => console.log("type", e.message)); await sleep(300); await page.keyboard.press("Enter");
};
await page.goto(`${BASE}/en?demo=shahada`, { waitUntil: "load", timeout: 90000 });
await page.getByRole("button", { name: /Start your journey/i }).first().waitFor({ timeout: 60000 });
await sleep(800);
await page.evaluate(() => window.scrollTo(0, 0));
mark("chat");
await smooth(-600, 20, 50); await sleep(1500); await smooth(900, 30, 60); await sleep(2000);
await page.getByRole("button", { name: /Start your journey/i }).first().click();
await sleep(2500);
await page.getByRole("button", { name: /^Continue/i }).first().click({ timeout: 8000 }).catch((e) => console.log("continue", e.message));
await sleep(1500);
mark("choices");
await sleep(2500);
await page.getByRole("button", { name: /^Ablution/i }).last().hover().catch(() => {}); await sleep(600);
await page.getByRole("button", { name: /^Ablution/i }).last().click();
mark("chose_wudu");
await page.getByText(/in brief|at a glance|summary/i).first().waitFor({ timeout: 60000 }).catch(async (e) => { console.log("brief", e.message); });
await sleep(1000);
mark("lesson1");
await sleep(3000);
await smooth(250); await sleep(800);
const marker = page.locator("main button").filter({ hasText: /^2$/ }).first();
await marker.click({ timeout: 8000 }).catch((e) => console.log("marker", e.message));
mark("source");
await sleep(3500);
await page.keyboard.press("Escape").catch(() => {});
await page.getByText(/From the (Noble )?Qur/i).first().scrollIntoViewIfNeeded({ timeout: 8000 }).catch((e) => console.log("verse", e.message));
await sleep(500);
mark("verse");
await sleep(3500);
await page.getByText(/Check your understanding/i).first().scrollIntoViewIfNeeded({ timeout: 8000 }).catch((e) => console.log("checkq", e.message));
await sleep(800);
mark("check");
await page.locator("input[type=radio]").first().check({ force: true, timeout: 8000 }).catch((e) => console.log("radio", e.message));
await sleep(700);
await page.getByRole("button", { name: "Check", exact: true }).first().click({ timeout: 8000 }).catch(() => {});
await sleep(2500);
await smooth(350); await sleep(500);
mark("exercises");
await page.getByRole("button", { name: "False", exact: true }).first().click({ timeout: 5000 }).catch(() => {});
await sleep(1500);
await page.getByRole("button", { name: "False", exact: true }).nth(1).click({ timeout: 5000 }).catch(() => {});
await sleep(2500);
mark("ask1");
await ask("What breaks wudu?");
await sleep(400);
mark("ask1_sent");
await page.getByText(/Al-Wajiz|p\. ?\d/i).last().waitFor({ timeout: 90000 }).catch(() => {});
await sleep(25000);
mark("ask1_answer");
await sleep(3000);
mark("ask2");
await ask("How do I make wudu?");
mark("ask2_sent");
await sleep(30000);
mark("ask2_answer");
await sleep(3000);
await page.getByRole("button", { name: /completed|next lesson|Next/i }).first().click({ timeout: 8000 }).catch((e) => console.log("next", e.message));
await sleep(6000);
mark("lesson2");
await sleep(2000);
await page.getByText(/steps/i).first().scrollIntoViewIfNeeded({ timeout: 8000 }).catch((e) => console.log("steps", e.message));
await sleep(500);
mark("steps");
await sleep(3000); await smooth(400, 25, 60); await sleep(2000);
await page.getByRole("button", { name: /Read the whole book/i }).first().click({ timeout: 8000 }).catch((e) => console.log("book", e.message));
await sleep(4000);
mark("book");
for (let i = 0; i < 4; i++) {
  const nx = page.getByRole("button", { name: /Next|Previous|›/i }).first();
  await nx.click({ timeout: 5000 }).catch(async () => { await page.keyboard.press("ArrowRight"); });
  await sleep(1800);
}
mark("book_end");
await sleep(1500);
await done();
