// Desktop (Arabic) learning space: chat, choices, lesson 1, sources, verse, check question, exercises,
// the ask panel (stages + sourced answers), the next lesson (wudu steps), the whole-book reader.
import { session, BASE } from "./lib.mjs";
const { page, mark, sleep, smooth, done } = await session("ls");
const ask = async (q) => {
  const box = page.getByPlaceholder(/اكتب سؤالك/).first();
  await box.click(); await box.pressSequentially(q, { delay: 45 }); await sleep(300); await page.keyboard.press("Enter");
};
await page.goto(`${BASE}/ar?demo=shahada`, { waitUntil: "load", timeout: 90000 });
await page.getByRole("button", { name: /ابدأ رحلتك/ }).first().waitFor({ timeout: 60000 });
await sleep(800);
await page.evaluate(() => window.scrollTo(0, 0));
mark("chat");
await smooth(-600, 20, 50); await sleep(1500); await smooth(900, 30, 60); await sleep(2000);
await page.getByRole("button", { name: /ابدأ رحلتك/ }).first().click();
await sleep(2500);
await page.getByRole("button", { name: "متابعة" }).first().click();
await sleep(1500);
mark("choices");
await sleep(2500);
await page.getByRole("button", { name: /^الوضوء/ }).last().hover(); await sleep(600);
await page.getByRole("button", { name: /^الوضوء/ }).last().click();
mark("chose_wudu");
await page.getByText("الدرس باختصار").first().waitFor({ timeout: 60000 });
await sleep(1000);
mark("lesson1");
await sleep(3000);
await smooth(250); await sleep(800);
const marker = page.locator("main button").filter({ hasText: /^2$/ }).first();
await marker.click().catch((e) => console.log("marker", e.message));
mark("source");
await sleep(3500);
await page.keyboard.press("Escape").catch(() => {});
await page.getByText("من القرآن الكريم").first().scrollIntoViewIfNeeded().catch(() => {});
await page.evaluate(() => window.scrollBy(0, 0));
await sleep(500);
mark("verse");
await sleep(3500);
await page.getByText("تأكد من فهمك").first().scrollIntoViewIfNeeded();
await sleep(800);
mark("check");
await page.locator("input[type=radio]").first().check({ force: true }).catch((e) => console.log("radio", e.message));
await sleep(700);
await page.getByRole("button", { name: "تحقق", exact: true }).first().click().catch(() => {});
await sleep(2500);
await smooth(350); await sleep(500);
mark("exercises");
await page.getByRole("button", { name: "خطأ", exact: true }).first().click().catch(() => {});
await sleep(1500);
await page.getByRole("button", { name: "خطأ", exact: true }).nth(1).click().catch(() => {});
await sleep(2500);
mark("ask1");
await ask("ما نواقض الوضوء؟");
await sleep(400);
mark("ask1_sent");
await page.getByText(/الوجيز، ص/).last().waitFor({ timeout: 90000 }).catch(() => {});
await sleep(25000);
mark("ask1_answer");
await sleep(3000);
mark("ask2");
await ask("كيف أتوضأ؟");
mark("ask2_sent");
await sleep(30000);
mark("ask2_answer");
await sleep(3000);
await page.getByRole("button", { name: /أتممت الدرس، التالي/ }).first().click().catch((e) => console.log("next", e.message));
await sleep(6000);
mark("lesson2");
await sleep(2000);
await page.getByText("الخطوات بلفظ الكتاب").first().scrollIntoViewIfNeeded().catch((e) => console.log("steps", e.message));
await sleep(500);
mark("steps");
await sleep(3000); await smooth(400, 25, 60); await sleep(2000);
await page.getByRole("button", { name: /تصفّح الكتاب كاملاً/ }).first().click().catch((e) => console.log("book", e.message));
await sleep(4000);
mark("book");
for (let i = 0; i < 4; i++) {
  const nx = page.getByRole("button", { name: /التالية|الصفحة التالية|›|السابقة/ }).first();
  await nx.click().catch(async () => { await page.keyboard.press("ArrowLeft"); });
  await sleep(1800);
}
mark("book_end");
await sleep(1500);
await done();
